Some changes
klipitkas/fs-go pull request #1
Opened 2019-10-21 11:46 UTC by ahoulgrave

I like your program as it's super simple, i just refactored a bit the code so it's clearer, hope it's ok for you. Please do review and comment.

Thanks for sharing

2019-10-21 11:47 UTC, ahoulgrave commented
Will add a Dockerfile

2019-11-05 20:27 UTC, klipitkas commented
Hey, thanks a lot for the contribution. There are some merge conflicts however that need to be resolved.

2019-11-05 20:33 UTC, klipitkas requested changes

2019-11-05 20:33 UTC, klipitkas commented on Dockerfile
> +FROM golang:1.13-alpine as base
We could use `scratch` as the base image in order to reduce the docker image size.

2019-11-05 20:33 UTC, klipitkas commented on README.md
> +Build image
```suggestion
To build a Docker image:
```

2019-11-05 20:33 UTC, klipitkas commented on README.md
> +Run it
```suggestion
Run it using Docker:
```

2019-11-05 20:33 UTC, klipitkas commented on README.md
> +Run in different port
```suggestion
To run it using a different port:
```

2019-11-05 20:33 UTC, klipitkas commented on README.md
> +docker run --rm -v $(pwd):/data -p 9000:9000 fs:local -addr :9000
```suggestion
docker run --rm -v $(pwd):/data -p 9000:9000 fs:local -port 9000
```

2019-11-05 20:59 UTC, merged